[package]
name = "voice_changer"
version = "1.0.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
aaudio = "0.1.1"
jni = "0.19.0"
dasp = { version = "0.11.0", features = ["all"] }
tdpsola = "0.1.0"
ringbuf = "0.2.5"
android_logger = "0.10"
log = "0.4.14"